GET http://localhost:3000/

###
// Get employee by id
GET http://localhost:3000/employee/2

### Insert employee
POST http://localhost:3000/employee/insert
Content-Type: application/json

{
    "name": "John",
    "salary": 5000
}

### Update employee

PUT http://localhost:3000/employee/4
Content-Type: application/json
{
    "name": "John",
    "salary": 3000
}

### Delete employee
DELETE http://localhost:3000/delete/4